server:
  port: 8100

spring:
  application:
    name: agent-server
  datasource:
    url: jdbc:postgresql://localhost:5432/verbex
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

internal:
  api-key: ${INTERNAL_API_KEY}

logging:
  level:
    org.springframework: INFO
    ai.verbex: DEBUG