server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/verbex
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 900000  # 15 minutes
  refreshExpiration: 604800000  # 7 days