server:
  port: ${PORT:8200}

spring:
  application:
    name: chat-server

  datasource:
    url: jdbc:postgresql://localhost:5432/verbex
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework: INFO
    ai.verbex: DEBUG